version: "3"

services:

  grafana:
    container_name: homey-grafana-grafana
    image: grafana/grafana:7.0.3
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
    volumes:
      - $PWD/data:/var/lib/grafana
    user: "104"
  webapp:
    container_name: homey-grafana-api
    build: .
    image: zzave/homey-grafana:latest
    restart: always
    ports:
    - 8080:8080
    volumes:
        - $PWD/settings:/home/node/.athom-cli

