version: "3"

services:

  grafana:
    container_name: hig-grafana
    image: grafana/grafana:7.0.3
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - $PWD/data:/var/lib/grafana
  webapp:
    container_name: hig-homey-insights-simple-json
    build: .
    image: zzave/homey-grafana:latest
    ports:
    - 8080:8080

